language: python

cache:
  pip: true
  timeout: 1000

sudo: false

python:
- '3.6'

os:
- linux

matrix:
  fast_finish: true

notifications:
  email: false

env:
  globals:
    - DISPLAY=:99.0

# repo branches to test
branches:
- master

install:
- pip install -U pip wheel --quiet
- pip install --upgrade setuptools --quiet
- pip install -r requirements.txt --quiet
- pip install pytest
- pip install pytest-coverage
- pip install coverage
- pip install coveralls
- python setup.py install

before_script:
# Needed to handle GUI or QT based tests (e.g. matplotlib.pyplot import)
- sh -e /etc/init.d/xvfb start
- sleep 3

script:
- pytest lvmsurveysim/test --cov lvmsurveysim --cov-report html

# branches:
#   except:
#     - new_datamodel
#     - mpl6_clean_tools

after_success:
- coveralls
