name: py36
dependencies:
- openssl
- pip
- python>=3.6
- readline
- setuptools
- wheel
- zlib
- pip:
  - ipython>=6.2.0
  - click
  - seaborn
  - numpy
  - scipy
  - astropy
  - pandas
  - matplotlib
  - Shapely
  - PyYAML
